export const GET_CONFIG = "GET_CONFIG";
export const GET_GENRES = "GET_GENRES";
export const SET_LOADING = "SET_LOADING";
export const REMOVE_LOADING = "REMOVE_LOADING";

// set the side nav
export const SET_SELECTED_MENU = "SET_SELECTED_MENU";
export const REMOVE_SELECTED_MENU = "REMOVE_SELECTED_MENU";

// get movies
export const FETCH_MOVIES_LOADING = "FETCH_MOVIES_LOADING";
export const FETCH_MOVIES_FINISHED = "FETCH_MOVIES_FINISHED";
export const FETCH_MOVIES_DISCOVER = "FETCH_MOVIES_DISCOVER";
export const FETCH_MOVIES_GENRE = "FETCH_MOVIES_GENRE";
export const FETCH_MOVIES_SEARCH = "FETCH_MOVIES_SEARCH";

// movie
export const FETCH_MOVIE_LOADING = "FETCH_MOVIE_LOADING";
export const FETCH_MOVIE_FINISHED = "FETCH_MOVIE_FINISHED";
export const FETCH_MOVIE = "FETCH_MOVIE";

// errors
export const INSERT_ERROR = "INSERT_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";

// recomendation movies
export const FETCH_RECOMMENDATIONS = "FETCH_RECOMMENDATIONS";
export const FETCH_RECOMMENDATIONS_LOADING = "FETCH_RECOMMENDATIONS_LOADING";
export const FETCH_RECOMMENDATIONS_FINISHED = "FETCH_RECOMMENDATIONS_FINISHED";
